core/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.urls import re_path
from django.conf.urls import handler404, handler500, handler403, handler400


urlpatterns = [
    path('', views.home_view, name='home'),
    path('ladders/', views.ladders, name='ladders'),
    path('my_teams/', views.my_teams, name='my_teams'),
    path('my_challenges_picker/', views.my_challenges_picker, name='my_challenges_picker'),
    path('my_matches_picker/', views.my_matches_picker, name='my_matches_picker'),
    path('disputes_picker/', views.disputes_picker, name='disputes_picker'),
    path('team_invites_picker/', views.team_invites_picker, name='team_invites_picker'),
    path('challenges_picker/', views.challenges_picker, name='challenges_picker'),
    path('matches_picker/', views.matches_picker, name='matches_picker'),
    path('results_picker/', views.results_picker, name='results_picker'),
]

sweatygames/urls.py
from django.contrib import admin
from django.urls import path, include  # Import the include function
from django.conf.urls.static import static
from django.conf import settings
from users.views import support_list, change_support_status, support_detail, create_suggestion, suggestion_list, change_suggestion_status, suggestion_detail, terms, email_verified_required, privacy_policy, request_verification, resend_verification, login_view, logout_view, player_ladder_view, banned_page, report_user, report_detail, admin_center, unban_user, banned_users_list, report_list, customize_profile_view, profile_view, redirect_after_steam_login, other_profile_view, report_bug, bug_report_list, bug_report_detail, change_bug_status
from teams.views import create_team, already_a_player, team_ladder, invitation_sent, invitation_already_sent, transfer_ownership, edit_team, user_is_teammate, send_invitation, pending_team_invites, accept_invitation, team_detail, remove_player_from_team, leave_team, deny_invitation, disband_team
from matches.views import dispute_under_review, support_request_success, rules, request_match_support, submit_results_success, dispute_conflict, team_not_eligible, decline_direct_challenge, match_farming, schedule_conflict, accept_challenge, accept_direct_challenge, create_challenge, challenges, match_details, submit_results, dispute_proofs_list, update_dispute_proof, dispute_proof_details, dispute_details, disputes_list, match_list, past_match_list, my_match_list, my_past_match_list, cancel_challenge, cancel_direct_challenge, my_challenges_view, dispute_expired, create_direct_challenge
from messaging.views import messages, message_details, send_message
from duos_teams.views import create_duos_team, duos_team_ladder, edit_duos_team, send_duos_invitation, duos_invitation_sent, pending_duos_team_invites, duos_invitation_already_sent, user_is_duos_teammate, deny_duos_invitation, accept_duos_invitation, duos_team_detail, remove_player_from_duos_team, transfer_duos_ownership, leave_duos_team, disband_duos_team
from duos_matches.views import create_duos_challenge, duos_dispute_proof_details, cancel_direct_duos_challenge, accept_direct_duos_challenge, decline_direct_duos_challenge, my_duos_challenges,  duos_support_list, duos_support_detail, change_duos_support_status, create_direct_duos_challenge, accept_duos_challenge, duos_challenges, cancel_duos_challenge, duos_match_details, update_duos_dispute_proof, submit_duos_results, duos_dispute_proofs_list, duos_dispute_details, duos_disputes_list, duos_match_list, past_duos_match_list, my_duos_match_list, request_duos_match_support, my_past_duos_match_list

urlpatterns = [
    path('yougottatryharderthanthathackercmonnow/', admin.site.urls),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('profile/', profile_view, name='profile'),
    path('profile/<str:username>/', other_profile_view, name='other_user_profile'),
    path('admin_center/', admin_center, name='admin_center'),
    path('banned-users/', banned_users_list, name='banned_users_list'),
    path('unban-user/', unban_user, name='unban_user'),

    #Allauth urls

    path('accounts/', include('allauth.urls')),
    

    path('request_verification/', request_verification, name='request_verification'),
    path('resend-verification/', resend_verification, name='resend_verification'),


    path('customize_profile/', customize_profile_view, name='customize_profile'),
    path('redirect_after_steam_login/', redirect_after_steam_login, name='redirect_after_steam_login'),
    path('banned/', banned_page, name='banned_page'),
    path('report_user/<str:username>/', report_user, name='report_user'),
    path('report/<int:report_id>/', report_detail, name='report_detail'),
    path('reports/', report_list, name='report_list'),
    path('report_bug/', report_bug, name='report_bug'),
    path('bug_report_list/', bug_report_list, name='bug_report_list'),
    path('bug_report_detail/<int:bug_report_id>/', bug_report_detail, name='bug_report_detail'),
    path('bug_report_detail/<int:bug_report_id>/change_status/', change_bug_status, name='change_bug_status'),
    path('create_suggestion/', create_suggestion, name='create_suggestion'),
    path('suggestion_detail/<int:suggestion_id>/', suggestion_detail, name='suggestion_detail'),
    path('suggestion_detail/<int:suggestion_id>/change_status/', change_suggestion_status, name='change_suggestion_status'),
    path('suggestion_list/', suggestion_list, name='suggestion_list'),

    #Team Links
    path('create_team/', create_team, name='create_team'),
    path('already_a_player/', already_a_player, name='already_a_player'),
    path('invitation_sent/', invitation_sent, name='invitation_sent'),
    path('invitation_already_sent/', invitation_already_sent, name='invitation_already_sent'),
    path('user_is_teammate/', user_is_teammate, name='user_is_teammate'),
    path('invite/<int:team_id>/', send_invitation, name='send_invitation'),

    path('pending_team_invites/', pending_team_invites, name='pending_team_invites'),
    path('accept_invitation/<int:invitation_id>/', accept_invitation, name='accept_invitation'),
    path('team/<int:team_id>/remove_player/<int:player_id>/', remove_player_from_team, name='remove_player_from_team'),
    path('team/<int:team_id>/leave/', leave_team, name='leave_team'),
    path('team/<int:team_id>/', team_detail, name='team_detail'),
    path('deny_invitation/<int:invitation_id>/', deny_invitation, name='deny_invitation'),
    path('disband_team/<int:team_id>/', disband_team, name='disband_team'),
    path('team/edit/<int:team_id>/', edit_team, name='edit_team'),
    path('team_ladder/', team_ladder, name='team_ladder'),
    path('player_ladder/', player_ladder_view, name='player_ladder'),
    path('transfer_ownership/<int:team_id>/<int:new_owner_id>/', transfer_ownership, name='transfer_ownership'),

    #Duos Team Links
    path('create_duos_team/', create_duos_team, name='create_duos_team'),
    path('duos_team_ladder/', duos_team_ladder, name='duos_team_ladder'),
    path('duos_team/edit/<int:team_id>/', edit_duos_team, name='edit_duos_team'),
    path('duos_invite/<int:team_id>/', send_duos_invitation, name='send_duos_invitation'),
    path('duos_invitation_sent/', duos_invitation_sent, name='duos_invitation_sent'),
    path('duos_invitation_already_sent/', duos_invitation_already_sent, name='duos_invitation_already_sent'),
    path('user_is_duos_teammate/', user_is_duos_teammate, name='user_is_duos_teammate'),
    path('accept_duos_invitation/<int:invitation_id>/', accept_duos_invitation, name='accept_duos_invitation'),
    path('deny_duos_invitation/<int:invitation_id>/', deny_duos_invitation, name='deny_duos_invitation'),
    path('pending_duos_team_invites/', pending_duos_team_invites, name='pending_duos_team_invites'),
    path('duos_team/<int:team_id>/', duos_team_detail, name='duos_team_detail'),
    path('duos_team/<int:team_id>/remove_player/<int:player_id>/', remove_player_from_duos_team, name='remove_player_from_duos_team'),
    path('transfer_duos_ownership/<int:team_id>/<int:new_owner_id>/', transfer_duos_ownership, name='transfer_duos_ownership'),
    path('duos_team/<int:team_id>/leave/', leave_duos_team, name='leave_duos_team'),
    path('disband_duos_team/<int:team_id>/', disband_duos_team, name='disband_duos_team'),


    #Match Links
    path('challenges/', email_verified_required(challenges), name='challenges'),
    path('create_challenge/', email_verified_required(create_challenge), name='create_challenge'),
    path('accept_challenge/<int:challenge_id>/', accept_challenge, name='accept_challenge'),
    path('accept_direct_challenge/<int:direct_challenge_id>/', accept_direct_challenge, name='accept_direct_challenge'),
    path('create_direct_challenge/<int:team_id>/', email_verified_required(create_direct_challenge), name='create_direct_challenge'),
    path('cancel_challenge/<int:challenge_id>/', cancel_challenge, name='cancel_challenge'),
    path('cancel_direct_challenge/<int:direct_challenge_id>/', cancel_direct_challenge, name='cancel_direct_challenge'),
    path('match/<int:match_id>/', match_details, name='match_details'),
    path('match/<int:match_id>/submit_results/', submit_results, name='submit_results'),
    path('update_dispute_proof/<int:proof_id>/', update_dispute_proof, name='update_dispute_proof'),
    path('dispute_proofs/', dispute_proofs_list, name='dispute_proofs_list'),
    path('dispute_proof/<int:proof_id>/', dispute_proof_details, name='dispute_proof_details'),
    path('dispute/<int:dispute_id>/', dispute_details, name='dispute_details'),
    path('disputes/', disputes_list, name='disputes_list'),
    path('matches/', match_list, name='match_list'),
    path('past_matches/', past_match_list, name='past_match_list'),
    path('my_matches/', my_match_list, name='my_match_list'),
    path('my_past_matches/', my_past_match_list, name='my_past_match_list'),
    path('my_challenges/', my_challenges_view, name='my_challenges'),
    path('decline_direct_challenge/<int:challenge_id>/', decline_direct_challenge, name='decline_direct_challenge'),

    path('schedule_conflict/', schedule_conflict, name='schedule_conflict'),
    path('match_farming/', match_farming, name='match_farming'),
    path('submit_results_success/', submit_results_success, name='submit_results_success'),
    path('dispute_expired/', dispute_expired, name='dispute_expired'),
    path('dispute_under_review/', dispute_under_review, name='dispute_under_review'),
    path('dispute_conflict/', dispute_conflict, name='dispute_conflict'),
    path('team_not_eligible/', team_not_eligible, name='team_not_eligible'),
    


    #Duos Match Links
    path('duos_challenges/', email_verified_required(duos_challenges), name='duos_challenges'),
    path('create_duos_challenge/', email_verified_required(create_duos_challenge), name='create_duos_challenge'),

users/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django_countries.fields import CountryField
from datetime import date
from django.core.exceptions import ValidationError
from django.utils.timezone import now
from timezone_field import TimeZoneField
from django.utils import timezone


class Badge(models.Model):
    name = models.CharField(max_length=100)
    icon = models.ImageField(upload_to='badge_photos/')
    description = models.TextField()

    def __str__(self):
        return self.name



class Profile(AbstractUser):
    #basic info fields
    bio = models.TextField(max_length=100, blank=True)
    birthday = models.DateField(default=date.today) 
    country = CountryField(default='US')
    profile_picture = models.ImageField(upload_to='profile_pics/', blank=True, null=True)
    timezone = TimeZoneField(default='UTC')
    
    #Social Links
    twitch_link = models.URLField(max_length=255, blank=True, null=True)
    twitter_link = models.URLField(max_length=255, blank=True, null=True)
    youtube_link = models.URLField(max_length=255, blank=True, null=True)
    activision_id = models.CharField(max_length=50, blank=True, null=True)
    gamertag = models.CharField(max_length=15, blank=True, null=True)
    psnid = models.CharField(max_length=16, blank=True, null=True)
    
    #Eligibility
    eligible = models.BooleanField(default=True)
    eligible_at = models.DateTimeField(default=now)

    #team fields
    current_team = models.ForeignKey('teams.Team', on_delete=models.SET_NULL, blank=True, null=True, related_name='members')
    current_duos_team = models.ForeignKey('duos_teams.DuosTeam', on_delete=models.SET_NULL, blank=True, null=True, related_name='duos_members')

    #Rating System Fields
    rating = models.FloatField(default=1000)
    wins = models.PositiveIntegerField(default=0)
    losses = models.PositiveIntegerField(default=0)

    strikes = models.PositiveIntegerField(default=0)

    is_banned = models.BooleanField(default=False)

    #Badges
    badges = models.ManyToManyField(Badge, related_name='users', blank=True)
    
    @property
    def formatted_rating(self):
        if self.rating >= 100:
            return "{:.0f}".format(self.rating / 100)
        else:
            return "0"


    def __str__(self):
        return f"{self.username} ({self.formatted_rating})"


class Report(models.Model):
    reporter = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='reports_filed')
    reported_user = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='reports_received')
    reason = models.TextField(max_length=1000)
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Report by {self.reporter} against {self.reported_user}"

class BugReport(models.Model):
    reporter = models.ForeignKey(Profile, on_delete=models.CASCADE)
    description = models.TextField()
    reported_at = models.DateTimeField(default=timezone.now)
    STATUS_CHOICES = [
        ('open', 'Open'),
        ('closed', 'Closed'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='open')

    def __str__(self):
        return f"Bug ID: {self.pk} - {self.reported_at}"

class Suggestion(models.Model):
    reporter = models.ForeignKey(Profile, on_delete=models.CASCADE)
    description = models.TextField()
    reported_at = models.DateTimeField(default=timezone.now)
    STATUS_CHOICES = [
        ('open', 'Open'),
        ('closed', 'Closed'),
    ]
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='open')

    def __str__(self):
        return f"Suggestion ID: {self.pk} - {self.reported_at}"

duos_matches/templates/accept_direct_duos_challenge.html
{% extends 'base.html' %}
{% load static %}
{% load tz %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card border-5 border-primary rounded-4 custom-shadow text-center mb-5">
          
          <div class="card-header border-primary text-center"><h1>Accept Challenge</h1></div>
            {% if request.user.current_duos_team %}
              <div class="card-body text-center">
                <form method="post">
                  {% csrf_token %}
                    <p class="p-1 bg-warning text-dark custom-shadow-warning rounded col-md-8 mx-auto"><i class="fa-regular fa-clock fa-beat-fade"></i> Starts In: {{ direct_challenge.scheduled_date|timeuntil }}</p>
                    <div class="form-group">
                        <label for="team">Your Team: </label> <a href="{% url 'duos_team_detail' team_id=user.current_duos_team.id %}" class="link-underline-dark link-light link-offset-1 link-underline-opacity-25 link-underline-opacity-0-hover">{{ user.current_duos_team.name }} ({{ user.current_duos_team.formatted_rating }})
                    </div>
                  
                    <div class="form-group">
                        <label for="team">Opposing Team: </label> <a href="{% url 'duos_team_detail' team_id=direct_challenge.challenging_team.id %}" class="link-underline-dark link-light link-offset-1 link-underline-opacity-25 link-underline-opacity-0-hover">{{ direct_challenge.challenging_team }} ({{ direct_challenge.challenging_team.formatted_rating }})</a>
                    </div>



                  <hr class="mx-auto custom-shadow-small border-4 rounded-3" style="width:40%">

                  

                  <div class="form-group">
                    <label for="challenge_players"><h4>Select 2 players from your team who will participate in the match:</h4></label>
                    <p>{{ form.challenge_players }}</p>
                  </div>


                  {% if form.errors %}
                    <div class="alert alert-danger">
                      <ul class="list-unstyled">
                        {% for field_errors in form.errors.values %}
                          {% for error in field_errors %}
                            <li>{{ error }}</li>
                          {% endfor %}
                        {% endfor %}
                      </ul>
                    </div>
                  {% endif %}
                  
                  
                </br>
                  

                

                  <button type="submit" class="btn btn-primary custom-shadow-small rounded-3 mb-3">Accept Challenge</button>

                </form>
                <hr class="mx-auto custom-shadow-small border-4 rounded-3" style="width:40%">

                <p>{{ challenge.scheduled_date|timezone:request.user.timezone }}</p>
                
                

                {% if direct_challenge.search_only %}
                    <p class="p-1 border border rounded-4 custom-shadow-small col-md-8 mx-auto"><i class="fa-solid fa-bomb fa-beat-fade"></i> Search & Destroy Only</p>
                {% else %}
                    <p class="p-1 border border rounded-4 custom-shadow-small col-md-8 mx-auto"><i class="fa-solid fa-circle-nodes fa-spin fa-spin"></i> All Gametypes</p>
                {% endif %}


                {% if direct_challenge.controller_only %}
                    <p class="p-1 border border rounded-4 custom-shadow-small col-md-8 mx-auto"><i class="fa-solid fa-gamepad fa-beat-fade"></i> Controller Only</p>
                {% else %}
                    <p class="p-1 border border rounded-4 custom-shadow-small col-md-8 mx-auto"><i class="fa-solid fa-keyboard fa-beat-fade"></i> Any Input</p>
                {% endif %}

              </div>
            {% else %}
            <div class="card-body text-center">
              <h3>You need to be a member of a team to accept a challenge.</h3>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

duos_matches/templates/accept_duos_challenge.html
{% extends 'base.html' %}
{% load static %}
{% load tz %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card border-5 border-primary rounded-4 custom-shadow text-center mb-5">
          
          <div class="card-header border-primary text-center"><h1>Accept Challenge</h1></div>
            {% if request.user.current_duos_team %}
              <div class="card-body text-center">
                <form method="post">
                  {% csrf_token %}
                    <p class="p-1 bg-warning text-dark custom-shadow-warning rounded col-md-8 mx-auto"><i class="fa-regular fa-clock fa-beat-fade"></i> Starts In: {{ challenge.scheduled_date|timeuntil }}</p>
                    <div class="form-group">
                        <label for="team">Your Team: </label> <a href="{% url 'duos_team_detail' team_id=user.current_duos_team.id %}" class="link-underline-dark link-light link-offset-1 link-underline-opacity-25 link-underline-opacity-0-hover">{{ user.current_duos_team.name }} ({{ user.current_duos_team.formatted_rating }})</a>
                    </div>
                  
                    <div class="form-group">
                        <label for="team">Opposing Team: </label> <a href="{% url 'duos_team_detail' team_id=challenge.team.id %}" class="link-underline-dark link-light link-offset-1 link-underline-opacity-25 link-underline-opacity-0-hover">{{ challenge.team }} ({{ challenge.team.formatted_rating }})</a>
                    </div>



                  <hr class="mx-auto custom-shadow-small border-primary border-4 rounded-3" style="width:40%">

                  

                  <div class="form-group">
                    <label for="challenge_players"><h3>Select 2 players from your team to participate in the match:</h3></label>
                    <p>{{ form.challenge_players }}</p>
                  </div>


                  {% if form.errors %}
                    <div class="alert alert-danger">
                      <ul class="list-unstyled">
                        {% for field_errors in form.errors.values %}
                          {% for error in field_errors %}
                            <li>{{ error }}</li>
                          {% endfor %}
                        {% endfor %}
                      </ul>
                    </div>
                  {% endif %}
                  
                  
                </br>
                  

                

                  <button type="submit" class="btn btn-primary custom-shadow-small rounded-3 mb-3">Accept Challenge</button>

                </form>
                <hr class="mx-auto custom-shadow-small border-primary border-4 rounded-3" style="width:40%">

                <p>{{ challenge.scheduled_date|timezone:request.user.timezone }}</p>
                
                

                {% if challenge.search_only %}
                    <p class="p-1 border border rounded-4 custom-shadow-small col-md-8 mx-auto"><i class="fa-solid fa-bomb fa-beat-fade"></i> Search & Destroy Only</p>
                {% else %}
                    <p class="p-1 border border rounded-4 custom-shadow-small col-md-8 mx-auto"><i class="fa-solid fa-circle-nodes fa-spin fa-spin"></i> All Gametypes</p>
                {% endif %}


                {% if challenge.controller_only %}
                    <p class="p-1 border border rounded-4 custom-shadow-small col-md-8 mx-auto"><i class="fa-solid fa-gamepad fa-beat-fade"></i> Controller Only</p>
                {% else %}
                    <p class="p-1 border border rounded-4 custom-shadow-small col-md-8 mx-auto"><i class="fa-solid fa-keyboard fa-beat-fade"></i> Any Input</p>
                {% endif %}

              </div>
            {% else %}
            <div class="card-body text-center">
              <h3>You need to be a member of a team to accept a challenge.</h3>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

duos_matches/templates/create_direct_duos_challenge.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="card border-5 border-primary rounded-4 custom-shadow">
          <div class="card-header border-primary text-center">
            <h1>Sending direct challenge to <a href="{% url 'duos_team_detail' team_id=challenged_team.id %}" class="link-underline-dark link-light link-offset-1 link-underline-opacity-25 link-underline-opacity-0-hover">{{ challenged_team.name }}</h1></a>
          </div>
          {% if request.user.current_duos_team.full_team and request.user.current_duos_team.eligible and challenged_team.eligible %}
            <div class="card-body text-center">
              <form method="post">
                {% csrf_token %}


                <div class="form-group">
                  <label for="challenge_players">Select 2 players from {{ request.user.current_duos_team.name }} who will participate in the match:</label>
                  {{ form.challenge_players }}
                </div>

                {% if form.errors %}
                  <div class="alert alert-danger">
                    <ul>
                      {% for field_errors in form.errors.values %}
                        {% for error in field_errors %}
                          <li>{{ error }}</li>
                        {% endfor %}
                      {% endfor %}
                    </ul>
                  </div>
                {% endif %}
                
                </br>
                
                <div class="form-group">
                  <label for="scheduled_date">Match Date and Time:</label>
                  <input type="datetime-local" class="form-control mx-auto" id="scheduled_date" style="width: 50%;" name="scheduled_date" required>
                </div>

                </br>

                <div>
                  <div class="form-check form-check-inline ms-2">
                    <input class="form-check-input" type="checkbox" id="search_only" name="search_only">
                    <label class="form-check-label" for="search_only"><i class="fa-solid fa-bomb fa-beat-fade"></i>Search & Destroy Only</label>
                  </div>
                </div>  


                <div>
                  <div class="form-check form-check-inline ms-2">
                      </br>
                    <input class="form-check-input" type="checkbox" id="controller_only" name="controller_only">
                    <label class="form-check-label" for="controller_only"><i class="fa-solid fa-gamepad fa-beat-fade"></i> Controller Only</label>
                  </div>
                </div>


                </br>

                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#confirmCreateDirectChallengeModal">Send Direct Challenge</button>

                <!-- Modal for confirming challenge creation -->
                <div class="modal fade" id="confirmCreateDirectChallengeModal" tabindex="-1" aria-labelledby="confirmCreateDirectChallengeModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title ms-auto" id="confirmCreateDirectChallengeModalLabel">Confirm Create Direct Challenge</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        Are you sure you want to create this direct challenge?
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <button type="submit" class="btn btn-primary">Create Direct Challenge</button>
                      </div>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          {% else %}
            <div class="card-body text-center">
              <p>Must be owner or captain of a team with 4 players to create a direct challenge. Additionaly please be sure that the team you are challenging is eligible</p>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>



  <script>
    document.addEventListener("DOMContentLoaded", function() {
      // Get current date and time
      const now = new Date();
  
      // Calculate 30 minutes from now
      const thirtyMinutesLater = new Date(now.getTime() + 30 * 60000); // 30 minutes in milliseconds
  
      // Format today's date
      const year = now.getFullYear();
      let month = (now.getMonth() + 1).toString().padStart(2, '0');
      let day = now.getDate().toString().padStart(2, '0');
      const formattedDate = `${year}-${month}-${day}`;
  
      // Format 30 minutes later time
      let hours = thirtyMinutesLater.getHours().toString().padStart(2, '0');
      let minutes = thirtyMinutesLater.getMinutes().toString().padStart(2, '0');
      const formattedTime = `${hours}:${minutes}`;
  
      // Set the value of the scheduled_date input to today's date and time 30 minutes from now
      document.getElementById('scheduled_date').value = `${formattedDate}T${formattedTime}`;
    });
  </script>

{% endblock %}

duos_matches/templates/duos_support_request_form.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="row justify-content-center mx-auto">
        <div class="col-md-6 mx-auto">
            <div class="card border-5 border-primary mt-5 custom-shadow">
                <div class="card-header border-primary">
                <h1 class="card-title text-center">Support Request For<a class="link-underline-dark link-light link-offset-1 p-3 mt-3 link-underline-opacity-0 link-underline-opacity-0-hover" href="{% url 'duos_match_details' match.id %}">{{ match }}</a></h1>
                </div>
                <div class="card-body text-center">
                    <form method="POST">
                        {% csrf_token %}
                        <label for="id_category" class="form-label">Category:</label>
                        <select class="form-select" id="id_category" name="category">
                            {% for support_category in form.fields.category.queryset %}
                                <option value="{{ support_category.id }}">{{ support_category.category }}</option>
                            {% endfor %}
                        </select>


                        <div class="mb-3">
                            <label for="id_description" class="form-label">Description:</label>
                            <textarea class="form-control" id="id_description" name="description" rows="4"></textarea>
                        </div>

                        <div class="mb-3">
                            <label for="id_additional_evidence" class="form-label">Evidence:</label>
                            <textarea class="form-control" id="id_additional_evidence" name="additional_evidence" rows="4"></textarea>
                        </div>

                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}